lib/libopenswan/constants.c: fix build on uclibc-ng
xelerance/Openswan pull request #453
Opened 2020-11-28 20:38 UTC by ffontaine

Drop `ns_t_tkey` which is not used in the source code and not defined in uclibc-ng resulting in the following build failure:

```
openswan-2.6.52.2/lib/libopenswan/constants.c:1432:31: error: ‘ns_t_tkey’ undeclared here (not in a function)
 enum_names rr_qtype_names = { ns_t_tkey, ns_t_any
                               ^
```

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

2020-12-03 18:14 UTC, mohicks requested changes
This is definitely incorrect.  The first two arguments are a `<start>` and `<end>` of the enum range.

I guess the easiest change to get it working is to replace ns_t_tkey by ns_t_tsig-1.

The best solution is to add the ns_t_tkey to uclibc-ng and push a patch to them.

```
diff --git a/lib/libopenswan/constants.c b/lib/libopenswan/constants.c
index e1187d7..02a44fd 100644
--- a/lib/libopenswan/constants.c
+++ b/lib/libopenswan/constants.c
@@ -1429,7 +1429,8 @@ static const char *const rr_qtype_name[] = {
        NULL
     };
 
-enum_names rr_qtype_names = { ns_t_tkey, ns_t_any
+/* ns_t_tkey doesn't exist in uclibc-ng, so use ns_t_tsig-1 as the start value */
+enum_names rr_qtype_names = { ns_t_tsig - 1, ns_t_any
                              , rr_qtype_name, &rr_type_names };
 
 static const char *const rr_class_name[] = {
```

2020-12-03 19:49 UTC, ffontaine commented
I updated the PR as requested

2020-12-04 18:01 UTC, shussain commented
@ffontaine thank you for the PR.

While we appreciate the commit, it is for a workaround for a specific libc that we are puling into our repo. We feel the fix should be applied to the uclibc-ng  instead.

2020-12-04 18:01 UTC, closed without merging

2020-12-04 21:51 UTC, ffontaine commented
OK, then I'll disable openswan with uclibc-ng on buildroot as we can't expect that every uclibc-ng toolchains on the field will get patched any time soon.

2020-12-04 22:04 UTC, letoams commented
the real fix is to rip out that ancient bind4 code anyway. It's hasn't been used since freeswan days in 2003

libreswan is a dropin replacement (continuation fork)  and ripped out that code in 2011 and replaced it with libunbound code